# Generated by Django 3.2.5 on 2021-07-02 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 20, 20, 4, 555576)),
        ),
    ]
